version: '3.7'

services:

   cutom-postgres-11:
      build: ./postgres-11
      container_name: cutom-postgres-11
      environment:
         POSTGRES_USER: test
         POSTGRES_PASSWORD: test
         POSTGRES_DB: acme
      ports:
         - 5432:5432
